program kfmlibgen;

{$mode objfpc}{$H+}

// Compiles a .kfm form definition into Pascal source for a shared/static
// library exposing it via a small C-callable API. Given:
//
//   kfmlibgen <input.kfm> <outputDir> <LibBaseName>
//
// it writes two files into <outputDir>:
//   <LibBaseName>_impl.pas  - a plain unit: the .kfm file's contents,
//                             embedded as a string constant, parsed at
//                             unit initialization into a global
//                             TVMFormDefinition, plus the exported
//                             functions (marked "cdecl; public name") that
//                             read it. Compile this alone (fpc -a) and
//                             archive the .o with `ar` to get a .a.
//   <LibBaseName>_lib.lpr   - a thin `library` project that pulls in the
//                             impl unit and re-exports its functions.
//                             Compile this to get a .so/.dylib/.dll.
//
// See build_kfm_lib.sh, which drives both compiles for the host platform.

uses
  SysUtils, Classes, Math;

const
  ExportedFunctions: array[0..4] of String = (
    'kfm_form_name',
    'kfm_control_count',
    'kfm_control_name',
    'kfm_control_type',
    'kfm_get_property'
  );

function IIfStr(Cond: Boolean; const T, F: String): String;
begin
  if Cond then Result := T else Result := F;
end;

function PascalEscape(const Line: String): String;
begin
  Result := StringReplace(Line, '''', '''''', [rfReplaceAll]);
end;

function BuildEmbeddedConstant(const Lines: TStrings): String;
var
  I: Integer;
  SB: TStringList;
begin
  SB := TStringList.Create;
  try
    if Lines.Count = 0 then
      SB.Add('    ''''')
    else
      for I := 0 to Lines.Count - 1 do
        SB.Add(Format('    ''%s''%s', [PascalEscape(Lines[I]), IIfStr(I < Lines.Count - 1, ',', '')]));
    Result := SB.Text;
  finally
    SB.Free;
  end;
end;

procedure WriteImplUnit(const KfmLines: TStrings; const OutputDir, LibBaseName: String);
var
  UnitName: String;
  SL: TStringList;
begin
  UnitName := LibBaseName + '_impl';
  SL := TStringList.Create;
  try
    SL.Add('unit ' + UnitName + ';');
    SL.Add('');
    SL.Add('{$mode objfpc}{$H+}');
    SL.Add('');
    SL.Add('// GENERATED by kfmlibgen from a .kfm file - do not edit by hand.');
    SL.Add('');
    SL.Add('interface');
    SL.Add('');
    SL.Add('function kfm_form_name(buf: PAnsiChar; bufLen: LongInt): LongInt; cdecl; public name ''kfm_form_name'';');
    SL.Add('function kfm_control_count: LongInt; cdecl; public name ''kfm_control_count'';');
    SL.Add('function kfm_control_name(index: LongInt; buf: PAnsiChar; bufLen: LongInt): LongInt; cdecl; public name ''kfm_control_name'';');
    SL.Add('function kfm_control_type(index: LongInt): LongInt; cdecl; public name ''kfm_control_type'';');
    SL.Add('function kfm_get_property(controlName, propName: PAnsiChar; buf: PAnsiChar; bufLen: LongInt): LongInt; cdecl; public name ''kfm_get_property'';');
    SL.Add('');
    SL.Add('implementation');
    SL.Add('');
    SL.Add('uses');
    SL.Add('  SysUtils, Classes, VMUI, KfmParser;');
    SL.Add('');
    SL.Add('const');
    SL.Add('  KfmSourceLines: array[0..' + IntToStr(Max(KfmLines.Count - 1, 0)) + '] of AnsiString = (');
    SL.Add(BuildEmbeddedConstant(KfmLines));
    SL.Add('  );');
    SL.Add('');
    SL.Add('var');
    SL.Add('  GlobalFormDef: TVMFormDefinition;');
    SL.Add('');
    SL.Add('function CopyOut(const S: AnsiString; buf: PAnsiChar; bufLen: LongInt): LongInt;');
    SL.Add('begin');
    SL.Add('  if buf = nil then begin Result := -1; Exit; end;');
    SL.Add('  if bufLen <= Length(S) then begin Result := -1; Exit; end;');
    SL.Add('  if Length(S) > 0 then Move(S[1], buf^, Length(S));');
    SL.Add('  buf[Length(S)] := #0;');
    SL.Add('  Result := Length(S);');
    SL.Add('end;');
    SL.Add('');
    SL.Add('function kfm_form_name(buf: PAnsiChar; bufLen: LongInt): LongInt; cdecl;');
    SL.Add('begin');
    SL.Add('  Result := CopyOut(GlobalFormDef.Name, buf, bufLen);');
    SL.Add('end;');
    SL.Add('');
    SL.Add('function kfm_control_count: LongInt; cdecl;');
    SL.Add('begin');
    SL.Add('  Result := GlobalFormDef.Controls.Count;');
    SL.Add('end;');
    SL.Add('');
    SL.Add('function kfm_control_name(index: LongInt; buf: PAnsiChar; bufLen: LongInt): LongInt; cdecl;');
    SL.Add('begin');
    SL.Add('  if (index < 0) or (index >= GlobalFormDef.Controls.Count) then begin Result := -1; Exit; end;');
    SL.Add('  Result := CopyOut(TVMControl(GlobalFormDef.Controls[index]).Name, buf, bufLen);');
    SL.Add('end;');
    SL.Add('');
    SL.Add('function kfm_control_type(index: LongInt): LongInt; cdecl;');
    SL.Add('begin');
    SL.Add('  if (index < 0) or (index >= GlobalFormDef.Controls.Count) then begin Result := -1; Exit; end;');
    SL.Add('  Result := Ord(TVMControl(GlobalFormDef.Controls[index]).ControlType);');
    SL.Add('end;');
    SL.Add('');
    SL.Add('function kfm_get_property(controlName, propName: PAnsiChar; buf: PAnsiChar; bufLen: LongInt): LongInt; cdecl;');
    SL.Add('var');
    SL.Add('  I: Integer;');
    SL.Add('  Control: TVMControl;');
    SL.Add('begin');
    SL.Add('  Result := -1;');
    SL.Add('  if (controlName = nil) or (propName = nil) then Exit;');
    SL.Add('  for I := 0 to GlobalFormDef.Controls.Count - 1 do');
    SL.Add('  begin');
    SL.Add('    Control := TVMControl(GlobalFormDef.Controls[I]);');
    SL.Add('    if SameText(Control.Name, StrPas(controlName)) then');
    SL.Add('    begin');
    SL.Add('      Result := CopyOut(Control.GetPropertyValue(StrPas(propName)), buf, bufLen);');
    SL.Add('      Exit;');
    SL.Add('    end;');
    SL.Add('  end;');
    SL.Add('end;');
    SL.Add('');
    SL.Add('var');
    SL.Add('  I: Integer;');
    SL.Add('  KfmSourceList: TStringList;');
    SL.Add('initialization');
    SL.Add('  KfmSourceList := TStringList.Create;');
    SL.Add('  for I := Low(KfmSourceLines) to High(KfmSourceLines) do');
    SL.Add('    KfmSourceList.Add(KfmSourceLines[I]);');
    SL.Add('  GlobalFormDef := ParseKfmText(KfmSourceList);');
    SL.Add('  KfmSourceList.Free;');
    SL.Add('finalization');
    SL.Add('  GlobalFormDef.Free;');
    SL.Add('end.');

    SL.SaveToFile(IncludeTrailingPathDelimiter(OutputDir) + UnitName + '.pas');
  finally
    SL.Free;
  end;
end;

procedure WriteLibraryProject(const OutputDir, LibBaseName: String);
var
  LibName, ImplUnitName: String;
  SL: TStringList;
  I: Integer;
begin
  LibName := LibBaseName + '_lib';
  ImplUnitName := LibBaseName + '_impl';
  SL := TStringList.Create;
  try
    SL.Add('library ' + LibName + ';');
    SL.Add('');
    SL.Add('{$mode objfpc}{$H+}');
    SL.Add('');
    SL.Add('// GENERATED by kfmlibgen - thin shared-library wrapper around ' + ImplUnitName + '.pas.');
    SL.Add('');
    SL.Add('uses');
    SL.Add('  ' + ImplUnitName + ' in ''' + ImplUnitName + '.pas'';');
    SL.Add('');
    SL.Add('exports');
    for I := 0 to High(ExportedFunctions) do
      SL.Add('  ' + ExportedFunctions[I] + IIfStr(I < High(ExportedFunctions), ',', ';'));
    SL.Add('');
    SL.Add('begin');
    SL.Add('end.');

    SL.SaveToFile(IncludeTrailingPathDelimiter(OutputDir) + LibName + '.lpr');
  finally
    SL.Free;
  end;
end;

var
  InputKfm, OutputDir, LibBaseName: String;
  KfmLines: TStringList;
begin
  if ParamCount < 3 then
  begin
    Writeln('Usage: kfmlibgen <input.kfm> <outputDir> <LibBaseName>');
    Halt(1);
  end;

  InputKfm := ParamStr(1);
  OutputDir := ParamStr(2);
  LibBaseName := ParamStr(3);

  if not FileExists(InputKfm) then
  begin
    Writeln('Error: input .kfm file not found: ', InputKfm);
    Halt(1);
  end;
  ForceDirectories(OutputDir);

  KfmLines := TStringList.Create;
  try
    KfmLines.LoadFromFile(InputKfm);
    WriteImplUnit(KfmLines, OutputDir, LibBaseName);
    WriteLibraryProject(OutputDir, LibBaseName);
  finally
    KfmLines.Free;
  end;

  Writeln('Generated ', LibBaseName, '_impl.pas and ', LibBaseName, '_lib.lpr in ', OutputDir);
end.
