SEARCH_DIR("/lib/")
SEARCH_DIR("/usr/lib/")
SEARCH_DIR("./")
SEARCH_DIR("/workspace/source/")
SEARCH_DIR("/workspace/jvm/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/httpd22/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/zorba/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/zlib/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/xforms/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/x11/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/webidl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/vcl-compat/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/uuid/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/utmp/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/utils-pas2js/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/users/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/unzip/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/tplylib/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/tcl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/syslog/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/symbolic/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/svgalib/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/sqlite/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/sdl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl-unicode/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl-objpas/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl-generics/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl-extra/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl-console/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/rsvg/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/regexpr/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/pxlib/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/pthreads/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/ptc/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/proj4/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/postgres/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/pcap/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/paszlib/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/pastojs/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/pasjpeg/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/oracle/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/openssl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/opengles/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/opengl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/openal/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/oggvorbis/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/odbc/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/odata/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/numlib/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/newt/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/ncurses/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/mysql/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/modplug/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/mad/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/lua/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/libxml2/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/libvlc/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/libusb/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/libtar/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/libsee/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/libpng/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/libmicrohttpd/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/libmagic/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/libgd/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/libgc/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/libfontconfig/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/libffi/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/libenet/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/libcurl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/libcups/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/ldap/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/jni/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/imlib/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/imagemagick/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/iconvenc/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/ibase/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/httpd24/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/hermes/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/hash/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/gtk2/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/gtk1/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/googleapi/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/gnutls/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/gnome1/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/gmp/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/ggi/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/gdbm/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/gdbint/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fv/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fppkg/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fpmkunit/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fpindexer/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fpgtk/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fftw/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-xml/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-web/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-stl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-sound/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-sdo/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-res/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-report/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-registry/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-process/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-pdf/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-passrc/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-net/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-json/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-js/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-image/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-fpcunit/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-extra/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-db/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-base/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-async/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/fastcgi/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/dts/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/dbus/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/dblib/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/chm/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/cdrom/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/cairo/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/bzip2/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/bfd/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/aspell/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/a52/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/aarch64-linux/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/")
INPUT(
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/cprt0.o
/usr/lib/crti.o
/workspace/projects/lib/aarch64-linux/kayte.o
/workspace/projects/lib/aarch64-linux/kayte.or
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/system.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/lnfodwrf.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/exeinfo.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/strings.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/fpintres.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/objpas.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/sysutils.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/classes.o
/workspace/projects/lib/aarch64-linux/lexer.o
/workspace/projects/lib/aarch64-linux/parser.o
/workspace/projects/lib/aarch64-linux/tokendefs.o
/workspace/projects/lib/aarch64-linux/ast.o
/workspace/projects/lib/aarch64-linux/compiler.o
/workspace/projects/lib/aarch64-linux/assembler.o
/workspace/projects/lib/aarch64-linux/bytecodetypes.o
/workspace/projects/lib/aarch64-linux/virtualmachine.o
/workspace/projects/lib/aarch64-linux/bytecode.o
/workspace/projects/lib/aarch64-linux/testbytecode.o
/workspace/projects/lib/aarch64-linux/xmlparser.o
/workspace/projects/lib/aarch64-linux/sdk.o
/workspace/projects/lib/aarch64-linux/c99.o
/workspace/projects/lib/aarch64-linux/kayte2pce.o
/workspace/projects/lib/aarch64-linux/kaytelibloader.o
/workspace/projects/lib/aarch64-linux/c_backend.o
/workspace/projects/lib/aarch64-linux/kayte_compiler.o
/workspace/projects/lib/aarch64-linux/kayte_runtime.o
/workspace/projects/lib/aarch64-linux/kayte_loader.o
/workspace/projects/lib/aarch64-linux/kayte_vm.o
/workspace/projects/lib/aarch64-linux/mathlib.o
/workspace/projects/lib/aarch64-linux/kayte_sdl3.o
/workspace/projects/lib/aarch64-linux/kayte_sdl2.o
/workspace/projects/lib/aarch64-linux/kaytearm64elf.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/linux.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/unix.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/errors.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/sysconst.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/unixtype.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/baseunix.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/unixutil.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/types.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/typinfo.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/rtlconsts.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/math.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/fgl.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl-generics/generics.collections.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl-generics/generics.memoryexpanders.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl-generics/generics.defaults.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl-generics/generics.helpers.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl-generics/generics.strings.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl-generics/generics.hashes.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl-objpas/variants.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl-objpas/varutils.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-process/process.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-process/pipes.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/termio.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/ctypes.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-fpcunit/fpcunit.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-fpcunit/testregistry.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-fpcunit/testutils.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-fpcunit/testdecorator.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-xml/dom.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-xml/xmlread.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-xml/xmlutils.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-xml/dtdmodel.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-base/uriparser.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-xml/xmlreader.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/fcl-xml/xmltextreader.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/dynlibs.o
/usr/lib/fpc/3.2.2/units/aarch64-linux/rtl/dl.o
)
INPUT(
-lSDL3
-lSDL2
-lkaytearm64elf
-ldl
)
GROUP(
-lc
)
INPUT(
/usr/lib/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
