/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/sysinit.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/kayte.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/kayte.or
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/system.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/lnfodwrf.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/exeinfo.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/ctypes.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/baseunix.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/dl.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/strings.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/unixtype.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/sysctl.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/fpintres.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/objpas.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/sysutils.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/classes.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/paszlib/zipper.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-web/fphttpclient.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-json/fpjson.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-json/jsonparser.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-process/process.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/cli.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/bytecode.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/testbytecode.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/virtualmachine.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/xmlparser.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/simplehttpserver.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/sdk.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/c99.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/sys_ios.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/sys_mac.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/kayte2pce.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/kaytelibloader.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/n64.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/unix.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/errors.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/sysconst.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/initc.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/unixutil.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/types.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/typinfo.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/rtlconsts.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/sortbase.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/math.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/paszlib/zstream.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/paszlib/zbase.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/paszlib/gzio.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/hash/crc.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/paszlib/zdeflate.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/paszlib/zinflate.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/paszlib/trees.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/paszlib/adler.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/paszlib/infblock.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/paszlib/infutil.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/paszlib/infcodes.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/paszlib/inftrees.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/paszlib/inffast.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-net/ssockets.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-web/httpdefs.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-base/uriparser.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-base/base64.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-net/sslsockets.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl-extra/sockets.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-net/resolve.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-net/netdb.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-web/httpprotocol.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl-objpas/strutils.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-net/sslbase.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl-objpas/variants.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-base/contnrs.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl-objpas/varutils.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-json/jsonscanner.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-json/jsonreader.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-process/pipes.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/termio.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/kayteparser.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-fpcunit/fpcunit.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-fpcunit/testregistry.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-fpcunit/testutils.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-fpcunit/testdecorator.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-xml/dom.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-xml/xmlread.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-xml/xmlutils.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-xml/dtdmodel.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-xml/xmlreader.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-xml/xmltextreader.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-web/fphttpserver.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-web/fpweb.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-base/fpthreadpool.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl-objpas/dateutils.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-base/syncobjs.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl-objpas/system.timespan.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/pthreads/pthreads.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-web/fphttp.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-base/fptemplate.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/fcl-web/httproute.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/objc.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/objcbase.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/univint/MacOSAll.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/cocoaint/CocoaAll.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/macpas.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/blockrtl.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/univint/MacTypes.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/univint/CoreAudioTypes.o
/Users/pedro/fpcupdeluxe/fpc/units/aarch64-darwin/rtl/dynlibs.o
