/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/sysinit.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/basic.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/system.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/lnfodwrf.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/exeinfo.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/strings.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/objpas.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/cthreads.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/classes.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/baseunix.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/unix.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/unixtype.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/initc.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/sysctl.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/unixutil.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/ctypes.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/sysutils.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/types.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/typinfo.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/rtlconsts.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/errors.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/sysconst.o
/usr/local/lib/fpc/3.2.2/units/aarch64-darwin/rtl/math.o
