/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/sysinit.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/kayte.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/kayte.or
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/system.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/lnfodwrf.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/exeinfo.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/ctypes.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/baseunix.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/dl.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/strings.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/unixtype.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/sysctl.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/fpintres.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/objpas.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/sysutils.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/classes.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/lexer.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/parser.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/tokendefs.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/ast.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/compiler.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/assembler.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/bytecodetypes.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/virtualmachine.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/bytecode.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/testbytecode.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/xmlparser.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/sdk.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/c99.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/kayte2pce.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/kaytelibloader.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/c_backend.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/kayte_compiler.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/kayte_runtime.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/kayte_loader.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/kayte_vm.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/mathlib.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/kayte_sdl3.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/kayte_sdl2.o
/Users/pedro/Projects/kayte-lang/projects/lib/aarch64-darwin/kaytearm64.o
/Users/pedro/Projects/kayte-lang/projects/../kayte_arm64_emit.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/unix.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/errors.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/sysconst.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/initc.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/unixutil.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/types.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/typinfo.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/rtlconsts.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/math.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/fgl.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl-generics/generics.collections.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl-generics/generics.memoryexpanders.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl-generics/generics.defaults.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl-generics/generics.helpers.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl-generics/generics.strings.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl-generics/generics.hashes.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl-objpas/variants.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl-objpas/varutils.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-process/process.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-process/pipes.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/termio.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-fpcunit/fpcunit.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-fpcunit/testregistry.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-fpcunit/testutils.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-fpcunit/testdecorator.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-xml/dom.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-xml/xmlread.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-xml/xmlutils.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-xml/dtdmodel.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-base/uriparser.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-xml/xmlreader.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/fcl-xml/xmltextreader.o
/usr/local/lib/fpc/3.2.4/units/aarch64-darwin/rtl/dynlibs.o
