# Makefile.fpc for Kings Project

APP_NAME := kings
SRC_DIR := src
BUILD_DIR := build
TARGET := $(BUILD_DIR)/$(APP_NAME)
FPC := fpc

# Compiler and linker options
FPC_OPTS := -MObjFPC -S2 -CX -XX -O2
LINK_OPTS := 

# List of source files
SRC_FILES := $(wildcard $(SRC_DIR)/*.pas)

.PHONY: all clean

all: $(TARGET)

$(TARGET): $(SRC_FILES)
	$(FPC) $(FPC_OPTS) -o$(TARGET) $(SRC_FILES)

clean:
	rm -f $(BUILD_DIR)/$(APP_NAME)
	rm -f $(BUILD_DIR)/*.o $(BUILD_DIR)/*.ppu

