version: 2.3

executors:
  fpc-executor-linux:
    docker:
      - image: freepascal/fpc:latest
    environment:
      FPC_VERSION: '2021.10.0'
      FPC_PATH: '/usr/local/include/fp17'

  fpc-executor-windows:
    machine:
      image: windows-server-2022
    environment:
      FPC_VERSION: '2021.10.0'
      FPC_PATH: 'C:\fpc'

  fpc-executor-macos:
    macos:
      xcode: 14.0.0
    environment:
      FPC_VERSION: '2021.10.0'
      FPC_PATH: '/usr/local/include/fp17'

jobs:
  virtual-machine-linux:
    executor: fpc-executor-linux
    steps:
      - checkout
      - run:
          name: Compile Virtual Machine (Linux)
          command: /usr/bin/fpc -o output.pas your-source-file.cpp

  virtual-machine-windows:
    executor: fpc-executor-windows
    steps:
      - checkout
      - run:
          name: Compile Virtual Machine (Windows)
          command: fpc.exe -o output.pas your-source-file.cpp

  virtual-machine-macos:
    executor: fpc-executor-macos
    steps:
      - checkout
      - run:
          name: Compile Virtual Machine (macOS)
          command: fpc -o output.pas your-source-file.cpp

  bytecode-gen-linux:
    executor: fpc-executor-linux
    steps:
      - checkout
      - run:
          name: Generate Bytecode (Linux)
          command: /usr/bin/fpc -o output.exe your-source-file.pas

  bytecode-gen-windows:
    executor: fpc-executor-windows
    steps:
      - checkout
      - run:
          name: Generate Bytecode (Windows)
          command: fpc.exe -o output.exe your-source-file.pas

  bytecode-gen-macos:
    executor: fpc-executor-macos
    steps:
      - checkout
      - run:
          name: Generate Bytecode (macOS)
          command: fpc -o output.exe your-source-file.pas

  dtd-parser-linux:
    executor: fpc-executor-linux
    steps:
      - checkout
      - run:
          name: Parse DTD (Linux)
          command: /usr/bin/fdtdc -h your-program

  dtd-parser-windows:
    executor: fpc-executor-windows
    steps:
      - checkout
      - run:
          name: Parse DTD (Windows)
          command: fdtdc.exe -h your-program

  dtd-parser-macos:
    executor: fpc-executor-macos
    steps:
      - checkout
      - run:
          name: Parse DTD (macOS)
          command: fdtdc -h your-program

  test-server-linux:
    executor: fpc-executor-linux
    steps:
      - checkout
      - run:
          name: Build and Install Test Server (Linux)
          command: sh -c "make && make install"

workflows:
  version: 2
  build-and-test:
    jobs:
      - virtual-machine-linux
      - virtual-machine-windows
      - virtual-machine-macos
      - bytecode-gen-linux
      - bytecode-gen-windows
      - bytecode-gen-macos
      - dtd-parser-linux
      - dtd-parser-windows
      - dtd-parser-macos
      - test-server-linux

