const { runKayteCode, compileKayteCode } = require('./kayte-js-binding');

const kayteCode = `
  print "Hello from Kayte Lang!"
`;

console.log("Running Kayte Lang code...");
runKayteCode(kayteCode);

console.log("Compiling Kayte Lang code...");
const bytecode = compileKayteCode(kayteCode);
console.log("Generated Bytecode:", bytecode);

