// index.js
const { runKayteCode, compileKayteCode } = require('./kayte-js-binding');

// Sample Kayte code
const kayteCode = `
  print "Hello from Kayte Lang!"
`;

console.log("Running Kayte Lang code...");
runKayteCode(kayteCode);

// Compile Kayte Lang code
console.log("Compiling Kayte Lang code...");
const bytecode = compileKayteCode(kayteCode);
console.log("Generated Bytecode:", bytecode);

